config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'

  
  get "admin", to: "admin#ng"

  get "clients/ng", to: "clients#ng"
  get "clients/ng/*angular_route", to: "clients#ng"
  resources :clients, only: [ :index, :show ]

  resources :dashboard, only: [ :index ]
  get "dashboard/ng", to: "dashboard#ng"
  get "dashboard/ng/*angular_route", to: "dashboard#ng"

  resources :services, only: [ :index, :show ]
  get "services/showVideoLibrary", to: "services#showVideoLibrary"

  post "server/SaveVideo.php", to: "services#saveVideo", format: :text
  post "server/SaveVideo", to: "services#saveVideo"
  get "server/videoLibrary", to: "services#showVideoLibrary"
  get "server/sendVideoByEmail", to: "services#sendVideoByEmail"

  resources :videos, :photos

  #get 'services/index'
  #get 'services/show'
  #get 'services/showVideoLibrary'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  belongs_to :video_cloud
  belongs_to :video_category
  has_many :video_distributions
end

app/controllers/videos_controller.rb
require "fileutils"
require "ostruct"

class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  @@allowed_extensions = Hash["jpg jpeg gif png mp3 mp4 wma webm webp".split.collect { |vv| [vv, 1] }]
  @@allowed_mime_types = Hash["video/mp4 video/webm audio/mp3 audio/wma image/jpeg image/png image/gif image/webp".split.collect { |vv| [vv,1] }]

  # GET /videos
  # GET /videos.json
  def index
    if params[:keywords].present?
      @videos = Video.where("user_id = ? and description like ?", current_user.id, "%#{params[:keywords]}%").order("created_at desc")
    else
      @videos = Video.where(user: current_user)
    end


    respond_to do |format|
      format.html {
      }

      format.json {
        render json: { videos: @videos }
      }
    end

  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])


    respond_to do |format|
      format.html {
      }

      format.json {
        render json: { video: @video }
      }
    end

  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    uploaded_hash = params[:video] ## ActionDispatch::Http::UploadedFile - stupid video[video]
    uploaded_actiondispatch = uploaded_hash ## ["video"]

    description = params[:description]
    name = uploaded_actiondispatch.original_filename
    mime_type = uploaded_actiondispatch.content_type
    uploaded_io = uploaded_actiondispatch.tempfile

    @user = current_user

    @saveVideo = OpenStruct.new
    @saveVideo.error = nil

    if uploaded_io && name
      if @@allowed_mime_types[mime_type]
        bs = VideoCloud.find_by(:backing_store => "local")
        vc = VideoCategory.find_by(:category => "any")

        @saveVideo.original_name = name
        @saveVideo.basename = File.basename(name)
        @saveVideo.extension = File.extname(name)
        @saveVideo.mime_type = mime_type
        @saveVideo.file_size = uploaded_io.length
        @saveVideo.saved_basename = sprintf("client%03d-user%06d-%s-%s-%s", 1, @user.id, @user.email, Time.now.strftime("%Y%m%d%H%M%S"), @saveVideo.basename).gsub(/\s/, "")
        @saveVideo.saved_filename = Rails.root.join(bs.access, @saveVideo.saved_basename)

        case uploaded_io
        when StringIO
          @saveVideo.tempfile = "in-memory"
          File.open(@saveVideo.saved_filename, "wb") { |file| file.write(uploaded_io.read) }
        when Tempfile
          @saveVideo.tempfile = uploaded_io.path

          ## client001-user999999-useremail-yyyymmddhhmmss-filename
          FileUtils.move(uploaded_io.path, @saveVideo.saved_filename);

          @video = Video.create({:isSelect => false, :color => "none", :user => @user, :description => description, :resource_path => @saveVideo.saved_basename, :video_cloud => bs, :video_category => vc })
        else
          @saveVideo.error = "unknown class for uploaded_io: #{uploaded_io.class.to_s}"
        end
      else
        @saveVideo.error = "Invalid mime type #{mime_type}"
      end
    else
      @saveVideo.error = "Missing uploaded file"
    end

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.fetch(:video, {})
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="container">
<%= form_tag(video, :method => :post, :multipart => true, :remote => false, :class => "form-horizontal") do %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group input-group-lg">
    <%= label_tag :description, nil, class: "col-sm-2" %>
    <div class="col-sm-4">
      <%= text_field_tag :description, nil, placeholder: "Enter a description of the video here", class: "form-control" %>
    </div>
  </div>
  <div class="input-group input-group-lg">
    <%= label_tag :upload, "Video Upload", class: "col-sm-2" %>
    <div class="col-sm-4">
      <input type="file" name="video" accept="image/webm,video/mp4" class:="form-control" />
    </div>
  </div>
  <span class="input-group-btn">
    <%= submit_tag nil, class: "btn btn-primary btn-lg" %>
  </span>
<% end %>
</div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<header>
  <h1 class="h2">Video Search</h1>
</header>

<section class="search-form">
  <%= form_for :videos, method: :get do |ff| %>
    <div class="input-group input-group-lg">
      <%= label_tag :keywords, nil, class: "sr-only" %>
      <%= text_field_tag :keywords, nil, placeholder: "description", class: "form-control input-lg" %>
      <span class="input-group-btn">
        <%= submit_tag "Find Videos", class: "btn btn-primary btn-lg" %>
      </span>
    </div>
  <% end %>
</section>


<section class="search-results">
  <header>
    <h1 class="h3">Results</h1>
  </header>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Description</th>
        <th>Resource Path</th>
        <th>Category</th>
        <th>Backing</th>
        <th>Created</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.description %></td>
          <td><%= video.resource_path %></td>
          <td><%= video.video_category.description %></td>
          <td><%= video.video_cloud.description %></td>
          <td><%= l video.created_at.to_date %></td>
          <td><%= link_to 'Show', video %></td>
          <td><%= link_to 'Edit', edit_video_path(video) %></td>
          <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<header>
  <h1 class="h2">New Video</h1>
</header>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<section class="video-details">
  <video controls>
    <source src="<%= video_path File.basename(@video.resource_path) %>" type="video/webm">
    Your bowser is bad bad bad
  </video>
  <h2><%= @video.description %></h2>
  <h3><%= @video.resource_path %></h3>
  <h4><%= @video.video_category.description %></h4>
  <h4><%= @video.video_cloud.description %></h4>
  <h5>
    <small class="text-uppercase">Created</small>
    <%= l @video.created_at.to_date %></td>
  </h5>
  <% if @saveVideo %>
  <h4>Save Details</h4>
    Uploaded:   <%= @saveVideo.original_name %></p>
    Mime Type:  <%= @saveVideo.mime_type %></p>
    Extension:  <%= @saveVideo.extension %></p>
    Size:       <%= @saveVideo.file_size %></p>
    Temp Path:  <%= @saveVideo.tempfile %></p>
    Saved Path: <%= @saveVideo.saved_filename %></p>
  <% end %>
</section>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>