config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'

  
  get "admin", to: "admin#ng"

  get "clients/ng", to: "clients#ng"
  get "clients/ng/*angular_route", to: "clients#ng"
  resources :clients, only: [ :index, :show ]

  resources :dashboard, only: [ :index ]
  get "dashboard/ng", to: "dashboard#ng"
  get "dashboard/ng/*angular_route", to: "dashboard#ng"

  resources :services, only: [ :index, :show ]
  get "services/showVideoLibrary", to: "services#showVideoLibrary"

  post "server/SaveVideo.php", to: "services#saveVideo", format: :text
  post "server/SaveVideo", to: "services#saveVideo"
  get "server/videoLibrary", to: "services#showVideoLibrary"
  get "server/sendVideoByEmail", to: "services#sendVideoByEmail"

  resources :videos, :photos

  #get 'services/index'
  #get 'services/show'
  #get 'services/showVideoLibrary'
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  PAGE_SIZE = 10

  def ng
    @base_url = '/clients/ng'
    render :index
  end

  def index
    @page = (params[:page] || 0).to_i
    @page_size = (params[:page_size] || PAGE_SIZE).to_i

    if params[:keywords].present?
      @keywords = params[:keywords]
      client_search_term = ClientSearchTerm.new(@keywords)
      @clients = Client.where(client_search_term.where_clause, client_search_term.where_args).
        order(client_search_term.order).
        offset(@page_size * @page).
        limit(@page_size)
    else
      #@clients = []
      @clients = Client.all.limit(@page_size)
    end

    respond_to do |format|
      format.html {
        redirect_to clients_ng_path
      }
      format.json {
        render json: { clients: @clients }
      }
    end
  end

  def show
    client = Client.find(params[:id])
    respond_to do |format|
      format.json { render json: { client: client } }
    end
  end
end

app/views/clients/_pager.html.erb
<nav>
  <ul class="pager">
    <% if page > 0 %>
      <li class="previous">
        <%= link_to "&larr; Previous".html_safe, clients_path(keywords: keywords, page: page - 1), title: "Previous Page" %>
      </li>
    <% end %>
    <li class="next">
      <%= link_to "Next &rarr;".html_safe, clients_path(keywords: keywords, page: page + 1), title: "Next Page" %>
    </li>
  </ul>
</nav>

app/views/clients/index.html.erb
<section>
  <fidiyo-clients-app></fidiyo-clients-app>
</section>
<%= javascript_pack_tag "clients" %>